# Generated by Django 3.1.4 on 2021-02-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='meme_caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='memer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='meme_url',
            new_name='url',
        ),
    ]
